// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/exp/dune/app/users/cnguyen/lblpwgtools/CAFAna/tute/./cpv_joint_Multi_noSystem.C";

#endif
